// Unique Generalized Abbreviations: Given a word, write a function to generate all of its unique generalized abbreviations.
// A generalized abbreviation of a word can be generated by replacing each substring of the word with the count of characters 
// in the substring. Take the example of “ab” which has four substrings: “”, “a”, “b”, and “ab”. After replacing these substrings 
// in the actual word by the count of characters, we get all the generalized abbreviations: “ab”, “1b”, “a1”, and “2”.
// Note: All contiguous characters should be considered one substring.

// solution:
// Think of each character as having two choices:

// Keep the character.
// Abbreviate it.

// For "ab":

// a → keep or abbreviate
// b → keep or abbreviate

// That gives:

// keep a, keep b       → "ab"
// abbreviate a, keep b → "1b"
// keep a, abbreviate b → "a1"
// abbreviate both      → "2"

// A clean JavaScript solution uses BFS:


function generateAbbreviations(word) {
    const result = [];
  
    const queue = [
      {
        str: "",
        index: 0,
        count: 0
      }
    ];
  
    while (queue.length > 0) {
      const current = queue.shift();
  
      // Finished processing the whole word
      if (current.index === word.length) {
        let abbreviation = current.str;
  
        // If some characters are still being abbreviated,
        // append their count
        if (current.count > 0) {
          abbreviation += current.count;
        }
  
        result.push(abbreviation);
        continue;
      }
  
      // Choice 1: abbreviate current character
      queue.push({
        str: current.str,
        index: current.index + 1,
        count: current.count + 1
      });
  
      // Choice 2: keep current character
      queue.push({
        str:
          current.str +
          (current.count > 0 ? current.count : "") +
          word[current.index],
        index: current.index + 1,
        count: 0
      });
    }
  
    return result;
}






// For:

// generateAbbreviations("ab");

// start with:

// str = ""
// index = 0
// count = 0

// We are looking at:

// word[0] = "a"

// Now we have two choices.

// If we abbreviate "a":

// str = ""
// count = 1
// index = 1

// Notice we don't immediately put "1" into str.

// We just remember:

// count = 1

// meaning:

// So far, 1 consecutive character has been abbreviated.

// The other choice is to keep "a":

// str = "a"
// count = 0
// index = 1

// So after processing "a" we have two states:

// abbreviate a:
// str = ""
// count = 1

// keep a:
// str = "a"
// count = 0

// Now process "b".

// From the first state:

// str = ""
// count = 1

// we can abbreviate "b" too.

// Then:

// count = 2

// So at the end:

// "2"

// because two consecutive characters were abbreviated.

// Or we can keep "b".

// Before keeping "b", we first write the pending count:

// count = 1

// then "b":

// "1" + "b"

// giving:

// "1b"

// Now take the other state:

// str = "a"
// count = 0

// If we abbreviate "b":

// str = "a"
// count = 1

// At the end, append that count:

// "a1"

// If we keep "b":

// "ab"

// So final output:

// ["2", "1b", "a1", "ab"]

// Same answers as:

// ab
// 1b
// a1
// 2

// The most important idea is what count means.

// count

// means:

// How many consecutive characters have I currently chosen to abbreviate?

// For example, with:

// word = "BAT"

// suppose we abbreviate:

// B
// A

// Then:

// count = 2

// If we decide to keep T, we first write the 2:

// 2T

// That is why this part exists:

// current.count > 0 ? current.count : ""

// before:

// word[current.index]

// It says:

// If I was abbreviating some previous consecutive characters, write their count before adding the current real character.

// Also, contiguous abbreviated characters are combined into one number:

// B and A abbreviated

// not:
// 11T

// but:
// 2T

// So the core pattern is:

// For every character:

// abbreviate it
// → count++

// keep it
// → write count if needed
// → write character
// → reset count to 0

// For a word of length n, there are 2^n generalized abbreviations because every character has two choices: keep or abbreviate.

// Today 5:56 PM

// current.index === word.length

// why are we comparing index with length and not length-1, when we know index is starting from 0

// Because here index does not mean “the last valid array/string index.” It means:

// Which character should I process next?

// That difference is the key.

// For:

// word = "ab"

// the indexes are:

// index: 0   1
// char:  a   b

// And:

// word.length === 2

// Now watch how index changes:

// index = 0 → process "a"
// index = 1 → process "b"
// index = 2 → nothing left to process

// So when:

// current.index === word.length

// that means:

// 2 === 2

// We have already processed every character.

// That is why this is correct:

// if (current.index === word.length)

// If we used:

// if (current.index === word.length - 1)

// then for "ab":

// word.length - 1 = 1

// We would stop when:

// index = 1

// But index 1 is "b":

// index: 0   1
// char:  a   b
//            ↑

// So "b" would never get processed.

// A useful way to think about it is:

// length - 1
// → last valid character index

// length
// → position just AFTER the last character

// For "abc":

// index:   0   1   2
// char:    a   b   c

// length = 3

// Processing goes:

// index 0 → process a
// index 1 → process b
// index 2 → process c
// index 3 → done

// So:

// index === word.length

// means we are done processing the word.

// This is the same reason a normal loop usually does:

// for (let i = 0; i < word.length; i++)

// The loop processes:

// 0, 1, 2

// and stops when:

// i = 3 = word.length

// So remember:

// Need last valid index?
// → length - 1

// Need to know "have I processed everything?"
// → index === length
